---
- name: building ci
  hosts: localhosts
  become: true
  become_user: root
  tasks:
    - name: Running mvn clean to create .war file
      command: "mvn package"
      chdir: "/var/lib/jenkins/workspace/jenkins_ci/project/CI-usingAnsible"
