---
- name: building ci
  hosts: localhost
  #become: true
  #become_user: root
  tasks:
    - name: Running mvn clean to create .war file
      command: "mvn package"
      args:
        chdir: "/var/lib/jenkins/workspace/jenkins_ci/project"
